### ISSUE TITLE
Docker build will fail if go.mod is updated, but the golang version in the Dockerfile is omitted.

### ISSUE THREAD

**Issue by sbp-bvanb** [030/gomod-go-version-updater-action#44]
Optional option that will detect Dockerfile and update it as well.

* Add an additional input: dependabot_enabled.
* If dependabot_enabled, then trigger dependabot using webhook.
* Trigger dependabot only if PR is created.

**Comment by 030** [comment]
Closed in favor of https://github.com/030/gomod-go-version-updater-action/issues/63
